CREATE TABLE IF NOT EXISTS vendm.machine_item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    price       DECIMAL(13, 2) NOT NULL,
    product     VARCHAR(10) NOT NULL
);

INSERT INTO vendm.machine_item(id, price, product)
VALUES (1, 10.00, 'Coke');

INSERT INTO vendm.machine_item(id, price, product)
VALUES (2, 5.00, 'Simba');

INSERT INTO vendm.machine_item(id, price, product)
VALUES (3, 10.00, 'Doritos');

INSERT INTO vendm.machine_item(id, price, product)
VALUES (4, 20.00, 'Pritzel');

INSERT INTO vendm.machine_item(id, price, product)
VALUES (5, 15.00, 'Snack Bar');

INSERT INTO vendm.machine_item(id, price, product)
VALUES (6, 5.00, 'Water');

INSERT INTO vendm.machine_item(id, price, product)
VALUES (7, 10.00, 'Brownie');

INSERT INTO vendm.machine_item(id, price, product)
VALUES (8, 15.00, 'Fanta');

INSERT INTO vendm.machine_item(id, price, product)
VALUES (9, 20.00, 'Ice Tea');

CREATE TABLE IF NOT EXISTS vendm.currency_denominator_table
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    currency_denominator    DECIMAL NOT NULL
);

INSERT INTO vendm.currency_denominator_table(id, currency_denominator)
VALUES (1, 5);

INSERT INTO vendm.currency_denominator_table(id, currency_denominator)
VALUES (2, 5);

INSERT INTO vendm.currency_denominator_table(id, currency_denominator)
VALUES (3, 5);

INSERT INTO vendm.currency_denominator_table(id, currency_denominator)
VALUES (4, 10);

INSERT INTO vendm.currency_denominator_table(id, currency_denominator)
VALUES (5, 10);

INSERT INTO vendm.currency_denominator_table(id, currency_denominator)
VALUES (6, 10);

INSERT INTO vendm.currency_denominator_table(id, currency_denominator)
VALUES (7, 20);

INSERT INTO vendm.currency_denominator_table(id, currency_denominator)
VALUES (8, 20);

INSERT INTO vendm.currency_denominator_table(id, currency_denominator)
VALUES (9, 20);

INSERT INTO vendm.currency_denominator_table(id, currency_denominator)
VALUES (10, 20);

INSERT INTO vendm.currency_denominator_table(id, currency_denominator)
VALUES (11, 20);